#!/bin/bash
# https://github.com/guomingyi/ui-gtk-3.0

if [ "y$1" = yv ]; then
    git remote add origin https://github.com/guomingyi/ui-gtk-3.0
    exit 0
fi

git add --all
git commit -am "<$1>"
git push -u origin master

exit 0
