#!/bin/bash
# build libusb for linux-amd64

cd libusb-1.0.22

./configure --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --prefix=$PWD/../ CC=x86_64-linux-gnu-gcc CXX=x86_64-linux-gnu-g++ --disable-udev

make -j8 && make install && make clean 

cd ..
